const PRELOAD_BASE_SCORE = 1;
const TRANSITION_FREQUENCY_REFERENCE_SET = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89];
const TRANSITION_FREQUENCY_REFERENCE_LOGS = TRANSITION_FREQUENCY_REFERENCE_SET.map((value) =>
  Math.log(value)
);
const TRANSITION_FREQUENCY_LOG_MEAN =
  TRANSITION_FREQUENCY_REFERENCE_LOGS.reduce((sum, value) => sum + value, 0) /
  TRANSITION_FREQUENCY_REFERENCE_LOGS.length;
const TRANSITION_FREQUENCY_LOG_SD = Math.sqrt(
  TRANSITION_FREQUENCY_REFERENCE_LOGS.reduce(
    (sum, value) => sum + (value - TRANSITION_FREQUENCY_LOG_MEAN) ** 2,
    0
  ) / TRANSITION_FREQUENCY_REFERENCE_LOGS.length
);
const TRANSITION_FREQUENCY_SIGMOID_SCALE = 2;

globalThis.ZeroLatencyPreloadScoringConstants = {
  PRELOAD_BASE_SCORE,
  TRANSITION_FREQUENCY_REFERENCE_SET,
  TRANSITION_FREQUENCY_LOG_MEAN,
  TRANSITION_FREQUENCY_LOG_SD,
  TRANSITION_FREQUENCY_SIGMOID_SCALE,
};
