(function () {
  const DOWNLOAD_EXTENSION_SET = new Set([
    "7z",
    "apk",
    "appx",
    "bat",
    "bin",
    "bz2",
    "cmd",
    "crx",
    "deb",
    "dmg",
    "exe",
    "gz",
    "img",
    "iso",
    "jar",
    "msi",
    "msix",
    "pkg",
    "ps1",
    "rar",
    "reg",
    "rpm",
    "sh",
    "tar",
    "tgz",
    "torrent",
    "xpi",
    "xz",
    "zip",
  ]);
  const DOWNLOAD_MIME_HINTS = [
    "application/octet-stream",
    "application/x-msdownload",
    "application/x-msi",
    "application/zip",
    "application/x-7z-compressed",
    "application/x-rar-compressed",
    "application/x-tar",
    "application/gzip",
    "application/vnd.android.package-archive",
    "application/x-apple-diskimage",
  ];
  const DOWNLOAD_PATH_TOKENS = new Set([
    "attachment",
    "attachments",
    "download",
    "downloads",
    "downloadfile",
    "download-file",
    "export",
    "exports",
  ]);
  const SIDE_EFFECT_PATH_TOKENS = new Set([
    "cancel",
    "confirm",
    "delete",
    "destroy",
    "logout",
    "log-out",
    "remove",
    "signout",
    "sign-out",
    "unsubscribe",
  ]);
  const DOWNLOAD_QUERY_KEYS = new Set([
    "attachment",
    "content-disposition",
    "dl",
    "download",
    "export",
    "file",
    "filename",
    "response-content-disposition",
  ]);
  const SIDE_EFFECT_QUERY_VALUES = new Set([
    "cancel",
    "confirm",
    "delete",
    "destroy",
    "download",
    "export",
    "logout",
    "remove",
    "signout",
    "unsubscribe",
  ]);

  globalThis.ZeroLatencyPreloadSafetyRuleConstants = {
    DOWNLOAD_EXTENSION_SET,
    DOWNLOAD_MIME_HINTS,
    DOWNLOAD_PATH_TOKENS,
    SIDE_EFFECT_PATH_TOKENS,
    DOWNLOAD_QUERY_KEYS,
    SIDE_EFFECT_QUERY_VALUES,
  };
})();
